apiVersion: v1
kind: ConfigMap
metadata:
  name: elearning-config
  namespace: latihan
data:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_TIMEZONE: "UTC"
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"
  APP_MAINTENANCE_DRIVER: "file"
  APP_MAINTENANCE_STORE: "database"
  BCRYPT_ROUNDS: "12"
  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_LEVEL: "debug"
  DB_CONNECTION: "sqlite"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"
  CACHE_STORE: "database"
  MAIL_MAILER: "log"
